import 'dotenv/config'

export const env = {
  port: Number(process.env.PORT || 3001),
  corsOrigin: process.env.CORS_ORIGIN || 'http://localhost:3000',
  appUrl: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  agentStatsDatabaseUrl: process.env.AGENT_STATS_DATABASE_URL || process.env.DATABASE_URL || '',
  agentStatsWallets: process.env.AGENT_STATS_WALLETS || '',
  agentStatsSyncIntervalMs: Number(process.env.AGENT_STATS_SYNC_INTERVAL_MS || '120000'),
  enableLootpotWorker: process.env.ENABLE_LOOTPOT_WORKER === 'true',
  enableDiscordPriceWorker: process.env.ENABLE_DISCORD_PRICE_WORKER === 'true',
  discordBotToken: process.env.DISCORD_BOT_TOKEN || '',
  discordGuildId: process.env.DISCORD_GUILD_ID || '',
  discordPricePollIntervalMs: Number(process.env.DISCORD_PRICE_POLL_INTERVAL_MS || '600000'),
  discordPriceDatabaseUrl: process.env.DISCORD_PRICE_DATABASE_URL || process.env.AGENT_STATS_DATABASE_URL || process.env.DATABASE_URL || '',
  discordLootpotWebhookUrl: process.env.DISCORD_LOOTPOT_WEBHOOK_URL || '',
  discordBotAssetBaseUrl: process.env.DISCORD_BOT_ASSET_BASE_URL || process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  discordLootpotEmoji: process.env.DISCORD_LOOTPOT_EMOJI || '🪙',
  discordLootEmoji: process.env.DISCORD_LOOT_EMOJI || '🪙',
  discordUsdEmoji: process.env.DISCORD_USD_EMOJI || '💵',
  lootpotLookbackBlocks: BigInt(process.env.LOOTPOT_LOOKBACK_BLOCKS || '21600'),
  lootpotPollIntervalMs: Number(process.env.LOOTPOT_POLL_INTERVAL_MS || '120000'),
  lootpotWorkerTest: process.env.LOOTPOT_WORKER_TEST === 'true',
  rpcPrimary: process.env.RPC_URL_PRIMARY || 'https://mainnet.base.org',
  rpcFallback1: process.env.RPC_URL_FALLBACK_1 || 'https://base.llamarpc.com',
  rpcFallback2: process.env.RPC_URL_FALLBACK_2 || 'https://rpc.ankr.com/base',
  rpcFallback3: process.env.RPC_URL_FALLBACK_3 || 'https://base-rpc.publicnode.com',
  scanStartBlock: BigInt(process.env.LOYALTY_SCAN_START_BLOCK || process.env.DEPLOY_SCAN_START_BLOCK || '0'),
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
}
